config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  # pages routes
  get 'pages/about'
  get 'pages/contact'

  # rooms routes
  resources :rooms
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.create(room_params)
    if @room.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  private

    def room_params
      params.require(:room).permit(:name, :price, :image, :image_thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light bg-light">
  <div class="container">
    <%= link_to 'Windy Ways Inn', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <!-- <span class="navbar-toggler-icon"></span> -->
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "Home", root_path, class: "nav-item nav-link" %>
        <%= link_to "Rooms", rooms_path, class: "nav-item nav-link" %>
        <%= link_to "About", pages_about_path, class: "nav-item nav-link" %>
        <%= link_to "Contact", pages_contact_path, class: "nav-item nav-link" %>
      </div>
    </div> <!-- div.collapse -->
  </div> <!-- div.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Windy Ways Inn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<form>
  <div class="row mb-3">
    <div class="col">
      <label for="firstNameInput">First Name</label>
      <input type="text" class="form-control" id="firstNameInput" aria-describedby="firstNameHelp" placeholder="First name">
    </div>
    <div class="col">
      <label for="lastNameInput">Last Name</label>
      <input type="text" class="form-control" id="lastNameInput" aria-describedby="lastNameHelp" placeholder="Last name">
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <label for="phoneInput">Phone Number</label>
      <input type="tel" class="form-control" id="phoneInput" aria-describedby="phoneHelp" placeholder="Phone Number">
    </div>
    <div class="col">
      <label for="emailInput">Email Address</label>
      <input type="email" class="form-control" id="emailInput" aria-describedby="emailHelp" placeholder="Email address">
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <label for="monthInFormControlSelect">Check In Month</label>
      <select class="form-control" id="monthInFormControlSelect">
        <option>January</option>
        <option>February</option>
        <option>March</option>
        <option>April</option>
        <option>May</option>
        <option>June</option>
        <option>July</option>
        <option>August</option>
        <option>Sepetember</option>
        <option>October</option>
        <option>November</option>
        <option>December</option>
      </select>
    </div>
    <div class="col">
      <label for="dateInFormControlSelect">Check In Day</label>
      <select class="form-control" id="dateInFormControlSelect">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
        <option>11</option>
        <option>12</option>
        <option>13</option>
        <option>14</option>
        <option>15</option>
        <option>16</option>
        <option>17</option>
        <option>18</option>
        <option>19</option>
        <option>20</option>
        <option>21</option>
        <option>22</option>
        <option>23</option>
        <option>24</option>
        <option>25</option>
        <option>26</option>
        <option>27</option>
        <option>28</option>
        <option>29</option>
        <option>30</option>
        <option>31</option>
      </select>
    </div>
  </div>
  <div class="row mb-3">
    <div class="col">
      <label for="monthOutFormControlSelect">Check Out Month</label>
      <select class="form-control" id="monthOutFormControlSelect">
        <option>January</option>
        <option>February</option>
        <option>March</option>
        <option>April</option>
        <option>May</option>
        <option>June</option>
        <option>July</option>
        <option>August</option>
        <option>Sepetember</option>
        <option>October</option>
        <option>November</option>
        <option>December</option>
      </select>
    </div>
    <div class="col">
      <label for="dateOutFormControlSelect">Check Out Day</label>
      <select class="form-control" id="dateOutFormControlSelect">
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
        <option>11</option>
        <option>12</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label for="questionsTextArea">Questions or Requests</label>
    <textarea class="form-control" id="questionsTextArea" rows="3"></textarea>
  </div>
  <button type="submit" class="btn button">Submit</button>
</form>

app/views/pages/about.html.erb
<div class="page-wrapper">
  <div class="showcase-image">
    <%= image_tag 'about_showcase_1.png', class: "w-100" %>
    <h1 class="showcase-banner">Quintessentially Nantucket</h1>
  </div>
  <div class="container-fluid">
    <div class="about-blurb">
      <p>Relaxed sophistication is the animating principle behind the Windy Ways
        Inn, where guests find a home base for Nantucket’s most exclusive
        experiences.</p>
    </div>

    <hr>

    <div class="directions">
      <h2>Getting Here</h2>
      <p>From Boston, New York City and points on Cape Cod, Nantucket is easy to reach
        by air or ferry. The Windy Ways Inn is just a few blocks once you disembark
        from the year-round Hy-line or seasonal Steamship Authority ferries (both
        depart from Hyannis, Cape Cod). For guests who fly, the inn is a 10-minute
        taxi ride. Car rentals are also available at the airport.</p>
    </div>

    <hr>

    <div class="by-air">
      <h2>By Air</h2>
      <p>Our local airport is the Nantucket Memorial Airport located at 14 airport road,
      Nantucket, MA. Jetblue Airlines, Delta Airlines, US Airways Express and United
      Airlines operate seasonal flights. Cape Air/Nantucket Airlines flies year-round
      from Hyannis and Boston Logan International Airport. Contact us in advance if
      you have questions about flying to Nantucket—there are several “in season”
      alternatives and we are happy to assist with travel plans.</p>
    </div>

    <hr>

    <div class="by-ferry">
      <h2>By Ferry</h2>
      <p>Hy-line Cruises offers high-speed ferries (1 hour) to Nantucket Island
        ear-round. You can find the schedule and rates on their website. The Nantucket
        Hy-line ferry terminal is located at 33 Straight Wharf, a 4-minute walk from
        the Windy Ways Inn. View walking directions here.</p>

      <p>Steamship Authority offers a high-speed passenger ferry (1 hour) as well as
        a traditional ferry (2 ¼ hours) for vehicles (reservations absolutely necessary)
        and passengers to Nantucket Island. Schedules and rates along with information
        for last-minute travel can be found on their website. View driving directions
        (4 minutes) from steamboat wharf to union street inn here and walking directions
        (7 minutes) here.</p>
    </div> <!-- div by-ferry end -->
  </div> <!-- div container-fluid end -->
  <footer>
    <div class="row social-media-links">
      <i class="col">
        <%= link_to "", 'https://www.facebook.com', class: "fab fa-facebook-square" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.instagram.com', class: "fab fab fa-instagram" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.twitter.com', class: "fab fab fa-twitter" %>
      </i>
    </div>
    <p>&copy; 2018 Windy Ways Inn</p>
  </footer>
</div> <!-- div page wrapper end -->

app/views/pages/contact.html.erb
<div class="page-wrapper">
  <div class="showcase-image">
    <%= image_tag 'contact_showcase_1.png', class: "w-100" %>
    <h1 class="showcase-banner">Contact Us</h1>
  </div>
  <div class="container-fluid">
    <div class="reservations">
      <h2>Reservations</h2>
      <h3>By Phone: 555-555-5555</h3>
      <p>Our Reservations Office is open Monday – Friday from 9:00 a.m. to 5:00 p.m.
           (USA East Coast Time).  If you call off-hours and leave a message, please
           include your day and evening phone numbers, so we may respond to your
           reservation request or inquiry.</p>
      <h3>By E-Mail:</h3>
      <p>You can email us at reservations@windywaysinn.com, or you can send us a message here:</p>
      <%= render 'form' %>
    </div>

    <hr>

    <div class="catering">
      <h2>Catering</h2>
      <h3>By Phone: 555-555-5556</h3>
      <p>Our kitchen is at your disposal.  If you are hosting an event and need to
      make any special requests, please let us know.</p>
      <h3>By E-mail:</h3>
      <p>You can email us at catering@windywaysinn.com, or you can send us a message here:</p>
      <%= render 'form' %>
    </div>

  </div> <!-- div container-fluid end -->
  <footer>
    <div class="row social-media-links">
      <i class="col">
        <%= link_to "", 'https://www.facebook.com', class: "fab fa-facebook-square" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.instagram.com', class: "fab fab fa-instagram" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.twitter.com', class: "fab fab fa-twitter" %>
      </i>
    </div>
    <p>&copy; 2018 Windy Ways Inn</p>
  </footer>
</div> <!-- div page wrapper end -->

app/views/pages/index.html.erb
<div class="page-wrapper">
  <div class="showcase-image">
    <div id="showcaseCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag 'showcase_1.png', class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag 'showcase_2.png', class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag 'showcase_3.png', class: "d-block w-100" %>
        </div>
      </div>
    </div>

    <h1 class="showcase-banner">Windy Ways Inn</h1>
  </div>


  <div class="container-fluid index">
    <div class="ordinary">
      <h2>30 Miles From Ordinary</h2>
      <p>Welcome to Windy Ways Inn—Nantucket’s standard bearer for exquisite interiors,
        impeccable service and exclusive experiences. Guests from New York City, New
        England and around the world travel by air and sea to unwind in style under our
        historic roof. Our award-winning inn makes the perfect home base for romantic
        retreats to the island in spring, summer and autumn. Plan your visit and see
        what’s new to do, taste and enjoy on Nantucket.</p>
    </div>

    <hr>

    <div class="location">
      <div class="row justify-content-center">
        <%= image_tag 'old_nantucket_map.png', class: "col-md-6 h-100" %>
        <div class="col-md-6">
          <h3>Amazing Location</h3>
          <p>Located just off Main Street, Windy Ways Inn is conveniently located to
          give you easy access to just about all Nantucket has to offer!  Main Street,
          the wharf, Children's Beach and Brant Point are an easy walk away.  If you
        need to cover more distance, the island shuttle bus stop is right around the block!</p>
        </div>
      </div>
    </div> <!-- div location end -->

    <hr>

    <div class="historic">
      <h2>Our Historic Building</h2>
      <p>Our building has been an integral part of Nantucket's history.  In the
      1700's it served as a whaling factory.  During 1845-1897 it was home to the
        mayor.  For the early part of the 20th century the town used it as a shelter
        for the town workers during the winter.  In 1957 it became the Windy Ways Inn
        you see today.</p>
      <div class="row historic_gallery">
        <%= image_tag 'interior_1.png', class: "col-sm-6 h-100 mb-4" %>
        <%= image_tag 'interior_2.png', class: "col-sm-6 h-100 mb-4" %>
      </div>
    </div> <!-- div historic end -->

  </div> <!-- div container-fluid end -->
  <footer>
    <div class="row social-media-links">
      <i class="col">
        <%= link_to "", 'https://www.facebook.com', class: "fab fa-facebook-square" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.instagram.com', class: "fab fab fa-instagram" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.twitter.com', class: "fab fab fa-twitter" %>
      </i>
    </div>
    <p>&copy; 2018 Windy Ways Inn</p>
  </footer>
</div> <!-- div page wrapper end -->

app/views/rooms/_form.html.erb
<table summary="Room Form Fields">
  <tr>
    <th>Room Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= f.number_field(:price) %></td>
  </tr>
  <tr>
    <th>Image</th>
    <td><%= f.file_field(:image) %></td>
  </tr>
</table>

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<div class="page-wrapper">
  <div class="showcase-image">
    <%= image_tag 'rooms_showcase_1.png', class: "w-100" %>
    <h1 class="showcase-banner">Luxurious Rooms</h1>
  </div>
  <div class="container-fluid">
    <div class="room-blurb">
      <h2>Uncompromising Style</h2>
      <p>Awake to the soft cross-breeze and sparkling daylight and let your eyes wander.
        Rich patterns, a hint of greenery, soft pastels and one-of-a-kind artwork come
        into focus. This moment of exquisite stillness begins every day at the union
        street inn. Luxury bath amenities by Malin + Goetz delight the senses while
        divine Frette and Matouk linens elevate your sleep experience. Moored in crisp,
        traditional Nantucket style, each of our 12 guest rooms is a showpiece with its
        own unique character.</p>
    </div>

    <hr>

    <div class="row">
      <% @rooms.each do |room| %>
        <div class="col-sm-6 mb-4">
          <%= link_to image_tag(room.image, class: "w-100 room-list-image"), room_path(room.id) %>
          <div class="room-number">
            <p><%= room.name %></p>
            <h4>No. <%= room.id %></h4>
            <p><%= room.price %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div> <!-- div container-fluid end -->
  <footer>
    <div class="row social-media-links">
      <i class="col">
        <%= link_to "", 'https://www.facebook.com', class: "fab fa-facebook-square" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.instagram.com', class: "fab fab fa-instagram" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.twitter.com', class: "fab fab fa-twitter" %>
      </i>
    </div>
    <p>&copy; 2018 Windy Ways Inn</p>
  </footer>
</div> <!-- div page wrapper end -->

app/views/rooms/new.html.erb
<div>
  <h2>Add Room To Database</h2>

  <%= form_for(@room, :url => rooms_path(@room.id)) do |f| %>

    <%= render :partial => 'form', :locals => {:f => f} %>

    <div class="form-buttons">
      <%= f.submit("Add Room to the Database") %>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="page-wrapper">
  <div class="container-fluid">
    <div class="my-2 room-back-link">
      <%= link_to '<< Back To Rooms', rooms_path %>
    </div>
    <%= image_tag @room.image, class: "w-100" %>
    <div class="room-info">
      <h2><%= @room.name %></h2>
      <p>Per nightly rate: $<%= @room.price %></p>
    </div>
    <div class="row features">
      <div class="col-sm-6 features-1">
        <h4>Features</h4>
        <ul>
          <li>300 sq.ft</li>
          <li>King high poster bed</li>
          <li>Second floor corner</li>
          <li>Fireplace</li>
          <li>TV's in sitting room and bedroom</li>
          <li>Wet Bar</li>
          <li>Compact Fridge</li>
          <li>Walk-in shower</li>
        </ul>
      </div>

      <div class="col-sm-6 features-2">
        <h4>Inn Amenities</h4>
        <ul>
          <li>Full, cooked-to-order breakfast</li>
          <li>Beach bags (towels, bottled water, magazines)</li>
          <li>Frette linens</li>
          <li>Matouk Duvets and bathrobes</li>
          <li>Bath amenities</li>
          <li>Bottled spring water</li>
          <li>Breakfast in bed, patio, dining room</li>
          <li>Free Wifi</li>
          <li>Hairdryers</li>
          <li>AM/FM radio</li>
          <li>Iron, ironing board</li>
          <li>Makeup mirror</li>
          <li>Lending library (books, magazines, newspapers</li>
          <li>Afternoon treats</li>
        </ul>
        </div>
    </div> <!-- div features end -->

    <hr>

    <div class="row">

    </div>
  </div> <!-- div container fluid end -->
  <footer>
    <div class="row social-media-links">
      <i class="col">
        <%= link_to "", 'https://www.facebook.com', class: "fab fa-facebook-square" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.instagram.com', class: "fab fab fa-instagram" %>
      </i>
      <i class="col">
        <%= link_to "", 'https://www.twitter.com', class: "fab fab fa-twitter" %>
      </i>
    </div>
    <p>&copy; 2018 Windy Ways Inn</p>
  </footer>
</div> <!-- div page wrapper end -->